/xyz/openbmc_project/inventory/system:
  sensorID: 0x01
  sensorType: 0x12
  eventReadingType: 0x6F
  offset: 0x02
/xyz/openbmc_project/sensors/temperature/LM75_48/critical_high:
  sensorID: 0x02
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/temperature/LM75_48/critical_low:
  sensorID: 0x02
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/temperature/LM75_49/critical_high:
  sensorID: 0x03
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/temperature/LM75_49/critical_low:
  sensorID: 0x03
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/temperature/LM75_4A/critical_high:
  sensorID: 0x04
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/temperature/LM75_4A/critical_low:
  sensorID: 0x04
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/temperature/LM75_4B/critical_high:
  sensorID: 0x05
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/temperature/LM75_4B/critical_low:
  sensorID: 0x05
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x02  
/xyz/openbmc_project/sensors/temperature/LM75_4C/critical_high:
  sensorID: 0x06
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/temperature/LM75_4C/critical_low:
  sensorID: 0x06
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x02      
  /xyz/openbmc_project/sensors/temperature/LM75_4D/critical_high:
  sensorID: 0x07
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/temperature/LM75_4D/critical_low:
  sensorID: 0x07
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x02
  /xyz/openbmc_project/sensors/temperature/LM75_4E/critical_high:
  sensorID: 0x08
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/temperature/LM75_4E/critical_low:
  sensorID: 0x08
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x02
  /xyz/openbmc_project/sensors/temperature/LM75_4F/critical_high:
  sensorID: 0x09
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/temperature/LM75_4F/critical_low:
  sensorID: 0x09
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x02
